import { StyleSheet } from "react-native";

import { screenWidth } from "../dimensions";
import { colors } from "../../utils/colors";
export const LoginScreenStyle = StyleSheet.create({
  button: {
    borderRadius: 20,
    shadowColor: "rgba(0,0,0,0.3)",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 0,
    width: "75%",
  },
  buttonContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 10,
    width: "60%",
  },
  buttonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "700",
  },
  content: {
    alignItems: "center",
    borderColor: "rgba(0,0,0, 0.3)",
    borderWidth: 5,
    flex: 1,
    justifyContent: "center",
    width: screenWidth - 60,
  },
  formContainer: {
    alignItems: "center",
    backgroundColor: colors.light,
    borderRadius: 10,
    height: "auto",
    marginHorizontal: "10%",
    marginTop: 24,
    padding: 12,
    shadowColor: "rgba(0,0,0,0.3)",
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 1,
    shadowRadius: 0,
    width: "80%",
  },
  formTitle: {
    alignItems: "center",
    fontFamily: "BungeeInline-Regular",
    fontSize: 20,
    fontWeight: "bold",
    marginVertical: 12,
    textAlign: "center",
  },
  input: {
    backgroundColor: "white",
    borderColor: colors.grey,
    borderRadius: 10,
    borderWidth: 0.2,
    fontSize: 14,
    marginTop: 5,
    marginVertical: 20,
    minWidth: "82%",
    paddingHorizontal: 15,
    paddingVertical: 10,
    padding: 5,
    shadowColor: "rgba(0,0,0,0.3)",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  inputContainer: {
    width: "80%",
  },
  title: {
    paddingTop: 20,
    position: "absolute",
    top: 50,
  },
});
