import { Platform, StyleSheet } from "react-native";

import { Colors, Typography, screenWidth, screenHeight, Spacing } from "../variables";
export const LoginScreenStyle = StyleSheet.create({
  button: {
    borderRadius: 20,
    elevation: 15,
    shadowColor: "rgba(0,0,0,0.3)",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 0,
    width: "75%",
  },
  buttonContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginVertical: Spacing.md,
    width: "60%",
  },
  buttonText: {
    color: "white",
    fontSize: Typography.fontSizes.lg,
    fontWeight: "700",
  },
  content: {
    alignItems: "center",
    borderColor: "rgba(0,0,0, 0.3)",
    borderWidth: 5,
    flex: 1,
    justifyContent: "center",
    width: screenWidth - 60,
  },
  emailDislaimer: {
    alignSelf: "center",
    color: Colors["primary-dark"],
    fontSize: Typography.fontSizes.sm,
    fontStyle: "italic",
  },
  formContainer: {
    alignItems: "center",
    backgroundColor: Colors.light,
    borderRadius: 10,
    elevation: 15,
    height: "auto",
    marginHorizontal: Spacing.lg,
    marginTop: Spacing.md,
    padding: Spacing.sm,
    shadowColor: "rgba(0,0,0,0.3)",
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 1,
    shadowRadius: 0,
    width: "80%",
  },
  formTitle: {
    alignItems: "center",
    fontFamily: "BungeeInline-Regular",
    fontSize: Typography.fontSizes.xxl,
    fontWeight: "bold",
    marginVertical: Spacing.md,
    textAlign: "center",
  },
  input: {
    backgroundColor: "white",
    borderColor: Colors.grey,
    borderRadius: Platform.OS === "ios" ? 10 : 2,
    borderWidth: 0.2,
    color: Colors["primary-dark"],
    fontSize: Typography.fontSizes.md,
    height: screenHeight / 20,
    marginTop: Spacing.md,
    marginVertical: Spacing.sm,
    minWidth: "90%",
    padding: 5,
    paddingHorizontal: Spacing.md,
    shadowColor: "rgba(0,0,0,0.5)",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 0,
    zIndex: 1,
  },
  inputContainer: {
    width: "95%",
  },
  title: {
    paddingTop: Spacing.xxxl,
    position: "absolute",
    top: Spacing.sm,
  },
});
